# Default initial velocities for panda's ros2_control fake system

initial_velocities:
  panda/finger_joint1: 0
  panda/joint1: 0
  panda/joint2: 0
  panda/joint3: 0
  panda/joint4: 0
  panda/joint5: 0
  panda/joint6: 0
  panda/joint7: 0
