# Default initial positions for panda's ros2_control fake system
initial_positions:
  panda/joint1: 0.0
  panda/joint2: -0.785
  panda/joint3: 0.0
  panda/joint4: -2.356
  panda/joint5: 0.0
  panda/joint6: 1.571
  panda/joint7: 0.785
  panda/finger_joint1: 0
