# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# As explained at
# https://moveit.picknik.ai/main/doc/examples/controller_configuration/controller_configuration_tutorial.html#example-controller-manager
# this configuration file configures an interface between the MoveIt! planning system
# and ROS2 controllers. The names provided here must match the names in ros2_controllers.yaml.
# When the moveit_manage_controllers move_group node's parameter is set to true,
# the ROS2 controllers are managed by MoveIt! according to the configurations here below.
moveit_simple_controller_manager:
  controller_names:
    - panda_arm_trajectory_controller
    - hand_controller

  panda_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - panda/joint1
      - panda/joint2
      - panda/joint3
      - panda/joint4
      - panda/joint5
      - panda/joint6
      - panda/joint7

  hand_controller:
    type: GripperCommand
    joints:
      - panda/finger_joint1
    action_ns: gripper_cmd
    default: true
