# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    panda_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

panda_arm_trajectory_controller:
  ros__parameters:
    joints:
      - panda/joint1
      - panda/joint2
      - panda/joint3
      - panda/joint4
      - panda/joint5
      - panda/joint6
      - panda/joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

hand_controller:
  ros__parameters:
    joint: panda/finger_joint1

panda_forward_position_controller:
  ros__parameters:
    joints:
      - panda/joint1
      - panda/joint2
      - panda/joint3
      - panda/joint4
      - panda/joint5
      - panda/joint6
      - panda/joint7
      - panda/finger_joint1
    interface_name: position

panda_forward_velocity_controller:
  ros__parameters:
    joints:
      - panda/joint1
      - panda/joint2
      - panda/joint3
      - panda/joint4
      - panda/joint5
      - panda/joint6
      - panda/joint7
    interface_name: velocity
