# This file contains the configuration of controllers used in simulation, plus a f/t sensor broadcaster

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    admittance_controller:
      type: acg_admittance_controller/AdmittanceController

    cartesian_pose_controller:
      type: cartesian_pose_controller/CartesianPoseController

    haptic_fb_controller:
      type: haptic_fb_controller/HapticFeedbackController

    haptic_ff_controller:
      type: haptic_ff_controller/HapticFeedforwardController

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: gazebo_force_torque_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: ft_sensing_frame

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

admittance_controller:
  ros__parameters:
    robot_name: ur5e
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    force_torque_sensor:
      name: gazebo_force_torque_sensor
      measure_frame: ft_sensing_frame
    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity
    command_interfaces:
      - pose
    reference_interfaces:
      - pose
    kinematics:
        plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
        plugin_package: kinematics_interface
        tip: screwdriver
    task_space_reference_frame: world
    interaction_filter:
      type: interaction_filters/AdmittanceFilter
      name: admittance_filter
    wrench_reference_frame: ft_sensing_frame
    task_space_command_controller: cartesian_pose_controller
    fixed_robot_orientation: false
    command_tolerance:
      translational_tolerance: 0.5
      rotational_tolerance: 0.5
    filter_chain:
      fixed_orientation:
        filter1:
          name: "unbiasing_filter"
          type: "unbiasing_filter/UnbiasingFilterDouble"
          params:
            number_of_stable_samples_for_bias: 50
            tolerance: 2.0
        filter2:
          name: "multi_channel_moving_average_filter"
          type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
          params:
            number_of_observations: 15
      variable_orientation:
        filter1:
          name: "gravity_compensation_filter"
          type: "gravity_compensation_filter/GravityCompensationFilterDouble"
          params:
            ft_sensing_frame_name: "ft_sensing_frame"
            gravity: [0.0, 0.0, -9.81]
        filter2:
          name: "unbiasing_filter"
          type: "unbiasing_filter/UnbiasingFilterDouble"
          params:
            number_of_stable_samples_for_bias: 50
            tolerance: 2.0
        filter3:
          name: "multi_channel_moving_average_filter"
          type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
          params:
            number_of_observations: 15
    force_limitation_enabled: false
    reference_scaling_gain: 0.006  # Must be set between 0.0 and 1.0
    filter_chain_scaling:
      filter1:
        name: "multi_channel_moving_average_filter_scaling"
        type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
        params:
          number_of_observations: 150
    logging_enabled: true
    admittance_filter:
      mass:
        - 50.0
        - 50.0
        - 50.0
        - 50.0
        - 50.0
        - 50.0
      damping_ratio:
        - 7.5
        - 7.5
        - 10.0
        - 7.5
        - 7.5
        - 7.5
      stiffness:
        - 20000.0
        - 20000.0
        - 6000.0
        - 20000.0
        - 20000.0
        - 20000.0
      order: 2  # Must be 0, 1 or 2
      compliant_axis: [true, true, true, false, false, false]

cartesian_pose_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    robot_name: ur5e
    use_velocity_state_interfaces: true
    use_task_space_twist: false
    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity
    joint_space_command_controller: "none"
    command_interfaces:
      - position
    command_interfaces_names_override:
      joint_position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
    task_space_reference_frame: world
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: screwdriver
    alpha: 0.000005
    k_matrix_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    joint_position_limits: [6.2832, 6.2832, 3.14159, 6.2832, 6.2832, 6.2832 ]
    joint_position_tolerance: 0.5

haptic_ff_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position
    downstream_controller_name: admittance_controller
    haptic_device_name: touch_haptic_device
    haptic_pose_subscriber:
      topic_name: /hd/haptic_pose_broadcaster/pose
      queue_size: 100
    haptic_twist_subscriber:
      topic_name: /hd/haptic_twist_broadcaster/twist
      queue_size: 100
    haptic_pose_rviz_publisher:
      topic_name: ~/haptic_pose_rviz
      frame_id: world
    reference_pose_publisher:
      topic_name: ~/reference_pose
      frame_id: world
    reference_twist_publisher:
      topic_name: ~/reference_twist
      frame_id: world
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: screwdriver
    engagement_orientation_threshold: 0.01
    RPY_robot_base_to_haptic_base: [1.5708, 0.0, 0.0]
    RPY_haptic_ee_to_tool_tip: [3.1416, 0.0, 0.0]
    robot_ee_to_TCP: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    scaling_factor: [1.0, 1.0, 1.5]
    robot_base_frame: "world"
    robot_ee_frame:  "screwdriver"
    simulation: true
    velocity_control: false
    haptic_device_interfaces:
      - touch_haptic_device/position.x
      - touch_haptic_device/position.y
      - touch_haptic_device/position.z
      - touch_haptic_device/orientation.x
      - touch_haptic_device/orientation.y
      - touch_haptic_device/orientation.z
      - touch_haptic_device/orientation.w
    filter_chain:
      filter1:
        name: "moving_average_poses_filter"
        type: "moving_average_poses_filter/MovingAveragePosesFilter"
        params:
          number_of_observations: 50

haptic_fb_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_interfaces:
      - position
      - gazebo_force_torque_sensor/force.x
      - gazebo_force_torque_sensor/force.y
      - gazebo_force_torque_sensor/force.z
      - gazebo_force_torque_sensor/torque.x
      - gazebo_force_torque_sensor/torque.y
      - gazebo_force_torque_sensor/torque.z
    simulation: true
    read_force_torque_from_topic: false
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: screwdriver
    force_filter_chain:
      filter1:
        name: "gravity_compensation_filter"
        type: "gravity_compensation_filter/GravityCompensationFilterDouble"
        params:
          ft_sensing_frame_name: "ft_sensing_frame"
          gravity: [0.0, 0.0, -9.81]
      filter2:
        name: "unbiasing_filter"
        type: "unbiasing_filter/UnbiasingFilterDouble"
        params:
          number_of_stable_samples_for_bias: 50
          tolerance: 0.001
      filter3:
        name: "multi_channel_moving_average_filter"
        type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
        params:
          number_of_observations: 100
    motion_error_filter_chain:
      filter1:
        name: moving_average_filter
        type: moving_average_filter/MultiChannelMovingAverageFilterDouble
        params:
          number_of_observations: 100
    robot_base_frame: world
    robot_ee_frame: screwdriver
    ft_measure_frame: ft_sensing_frame
    RPY_robot_base_to_haptic_base: [1.5708, 0.0, 0.0]
    haptic_force_controller: haptic_forward_force_controller
    enable_motion_error: false
    wrench_publisher:
      topic_name: ~/wrench
      frame_id: touch_haptic_device_base
    position_error_publisher:
      topic_name: ~/position_error
      frame_id: touch_haptic_device_base
    velocity_error_publisher:
      topic_name: ~/velocity_error
      frame_id: touch_haptic_device_base
    wrench_subscriber:
      topic_name: /force_torque_sensor_broadcaster/wrench
      queue_size: 100
    admittance_state_subscriber:
      topic_name: /admittance_controller/status
      queue_size: 100
