<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="screwdriver">
  <xacro:property name="name" value="screwdriver"/>

  <xacro:macro name="build_tool" params="mounting_link mounting_to_tool_joint:='' config sim_ignition:=^|false">
    <xacro:if value="${mounting_to_tool_joint == ''}">
      <xacro:property name="mounting_to_tool_joint" value="${mounting_link + '_to_' + name}"/>
    </xacro:if>

    <xacro:property name="mass" value="2.74"/>
    <xacro:property name="height" value="0.12"/>
    <xacro:property name="width" value="0.144"/>
    <xacro:property name="depth" value="0.085"/>

    <xacro:include filename="$(find acg_common_libraries)/xacro/define_property_from_dict.xacro"/>
    <xacro:define_property_from_dict input_dict="${config}" name="rpy" default_value="0 0 0"/>

    <material name="${name}_material_red">
      <color rgba="1.0 0.0 0.0 1.0"/>
    </material>

    <!-- Screwdriver -->

    <link name="${name}">
      <inertial>
        <origin xyz="-0.003 0.009 -0.19" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="0.008259" ixy="0" ixz="0" iyy="0.008259" iyz="0" izz="0.008259"/>
      </inertial>
      <visual>
        <origin xyz="${depth/2} ${height/2} ${-width/2}" rpy="0 1.5708 3.1421"/>
        <geometry>
          <mesh filename="file://$(find acg_resources_screwdriver_description)/meshes/visual/${name}.dae"/>
        </geometry>
        <material name="${name}_material_red"/>
      </visual>
      <collision>
        <origin xyz="${depth/2} ${height/2} ${-width/2}" rpy="0 1.5708 3.1421"/>
        <geometry>
          <mesh filename="file://$(find acg_resources_screwdriver_description)/meshes/collision/${name}.stl"/>
        </geometry>
        <surface>
          <contact>
            <ode>
              <solver>
                <type>world</type>
              </solver>
              <kp>1e15</kp>
              <kd>1e13</kd>
              <min_depth>0.0001</min_depth>
              <max_vel>0.1</max_vel>
            </ode>
          </contact>
        </surface>
      </collision>
    </link>

    <xacro:if value="${sim_ignition}">
      <gazebo reference="${name}">
        <gravity>true</gravity>
      </gazebo>
    </xacro:if>

    <!-- Fixed joint to connect the chalk holder tip with the previous link. -->

    <joint name="${mounting_to_tool_joint}" type="fixed">
      <origin xyz="0 ${width/2} ${height/2}" rpy="${rpy}"/>
      <parent link="${mounting_link}"/>
      <child link="${name}"/>
    </joint>

    <xacro:if value="${sim_ignition}">
      <gazebo reference="${mounting_to_tool_joint}">
        <provideFeedback>true</provideFeedback>
        <preserveFixedJoint>true</preserveFixedJoint>
      </gazebo>
    </xacro:if>
  </xacro:macro>
</robot>
