hd:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      haptic_pose_broadcaster:
        type: pose_broadcaster/PoseBroadcaster

      haptic_twist_broadcaster:
        type: twist_broadcaster/TwistBroadcaster

  haptic_pose_broadcaster:
    ros__parameters:
      pose_name: "touch_haptic_device"
      frame_id: "touch_haptic_device_base"

  haptic_twist_broadcaster:
    ros__parameters:
      twist_name: "touch_haptic_device"
      frame_id: "touch_haptic_device_base"
