# Based on Universal_Robots_ROS2_GZ_Simulation/ur_simulation_gz/config/ur_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    admittance_controller:
      type: acg_admittance_controller/AdmittanceController

    cartesian_pose_controller:
      type: cartesian_pose_controller/CartesianPoseController

    pid_controller:
      type: pid_controller/PidController

    haptic_ff_controller:
      type: haptic_ff_controller/HapticFeedforwardController

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: gazebo_force_torque_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: wrist_3_link

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

forward_velocity_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

admittance_controller:
  ros__parameters:
    robot_name: ur10
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    force_torque_sensor:
      name: gazebo_force_torque_sensor
      measure_frame: wrist_3_link
    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity
    use_twist_interface: false
    kinematics:
        plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
        plugin_package: kinematics_interface
        tip: wrist_3_link
    task_space_reference_frame: world
    interaction_filter:
      type: interaction_filters/AdmittanceFilter
      name: admittance_filter
    wrench_reference_frame: wrist_3_link
    task_space_command_controller: cartesian_pose_controller
    fixed_robot_orientation: false
    command_tolerance:
      translational_tolerance: 1.0
      rotational_tolerance: 1.0
    filter_chain:
      fixed_orientation:
        filter1:
          name: "unbiasing_filter"
          type: "unbiasing_filter/UnbiasingFilterDouble"
          params:
            number_of_stable_samples_for_bias: 50
            tolerance: 2.0
        filter2:
          name: "multi_channel_moving_average_filter"
          type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
          params:
            number_of_observations: 15
      variable_orientation:
        filter1:
          name: "gravity_compensation_filter"
          type: "gravity_compensation_filter/GravityCompensationFilterDouble"
          params:
            ft_sensor_link_name: "wrist_2_link"
            gravity: [0.0, 0.0, -9.81]
        filter2:
          name: "unbiasing_filter"
          type: "unbiasing_filter/UnbiasingFilterDouble"
          params:
            number_of_stable_samples_for_bias: 50
            tolerance: 2.0
        filter3:
          name: "multi_channel_moving_average_filter"
          type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
          params:
            number_of_observations: 15
    force_limitation_enabled: false
    reference_scaling_gain: 0.006  # Must be set between 0.0 and 1.0
    filter_chain_scaling:
      filter1:
        name: "multi_channel_moving_average_filter_scaling"
        type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
        params:
          number_of_observations: 150
    logging_enabled: true
    admittance_filter:
      mass:
        - 50.0
        - 50.0
        - 50.0
        - 50.0
        - 50.0
        - 50.0
      damping_ratio:
        - 7.5
        - 7.5
        - 10.0
        - 7.5
        - 7.5
        - 7.5
      stiffness:
        - 20000.0
        - 20000.0
        - 6000.0
        - 20000.0
        - 20000.0
        - 20000.0
      order: 2  # Must be 0, 1 or 2
      compliant_axis: [true, true, true, false, false, false]

cartesian_pose_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    robot_name: ur10
    use_twist_reference: true
    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity
    joint_space_command_controller: "pid_controller"
    command_interfaces:
      - position
    task_space_reference_frame: world
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: wrist_3_link

    alpha: 0.8
    k_matrix_gains: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
    joint_position_limits: [6.2832, 6.2832, 3.14159, 6.2832, 6.2832, 6.2832]
    joint_position_tolerance: 1.0

pid_controller:
  ros__parameters:
    dof_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interface: effort

    reference_and_state_interfaces: ["position", "effort"]

    gains:
      shoulder_pan_joint: {p: 1000.0, i: 5.0, d: 250.0, i_clamp_max: 0.0, i_clamp_min: 0.0}
      shoulder_lift_joint: {p: 100000.0, i: 10.0, d: 2000.0, i_clamp_max: 0.0, i_clamp_min: 0.0}
      elbow_joint: {p: 5000.0, i: 10.0, d: 250.0, i_clamp_max: 0.0, i_clamp_min: 0.0}
      wrist_1_joint: {p: 1000.0, i: 4.0, d: 10.0, i_clamp_max: 0.0, i_clamp_min: 0.0}
      wrist_2_joint: {p: 50.0, i: 3.0, d: 10.0, i_clamp_max: 0.0, i_clamp_min: 0.0}
      wrist_3_joint: {p: 30.0, i: 2.0, d: 0.05, i_clamp_max: 0.0, i_clamp_min: 0.0}

haptic_ff_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    state_interfaces:
      - position
      - velocity

    command_interfaces:
      - position
      - velocity

    downstream_controller_name: cartesian_pose_controller

    haptic_device_name: touch_haptic_device

    haptic_pose_subscriber:
      topic_name: /hd/haptic_pose_broadcaster/pose
      queue_size: 100

    haptic_twist_subscriber:
      topic_name: /hd/haptic_twist_broadcaster/twist
      queue_size: 100

    haptic_pose_rviz_publisher:
      topic_name: ~/haptic_pose_rviz
      frame_id: world

    reference_pose_publisher:
      topic_name: ~/reference_pose
      frame_id: world

    reference_twist_publisher:
      topic_name: ~/reference_twist
      frame_id: world

    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: wrist_3_link
      group_name: ur_manipulator
      alpha: 0.0005

    engagement_orientation_threshold: 0.01

    #RPY_robot_base_to_haptic_base: [1.5708, 0.0, 1.5708]
    RPY_robot_base_to_haptic_base: [1.5708, 0.0, -1.5708] #blackboard values

    RPY_haptic_ee_to_tool_tip: [3.1416, 0.0, 0.0]

    # Remote center of motion transform with respect to the end-effector frame in the form [roll, pitch, yaw, x, y, z]
    # The default transform represents the transformation from the robot end-effector to the tip of the the long handle,
    # mounted on a force torque sensor
    # robot_ee_to_TCP: [0.0, 0.0, 1.5708, 0.0, 0.0, 0.18]
    robot_ee_to_TCP: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    scaling_factor: [1.0, 1.0, 1.0]

    robot_base_frame: "world"

    robot_ee_frame:  "wrist_3_link"

    simulation: true
    velocity_control: false

    haptic_device_interfaces:
      - touch_haptic_device/position.x
      - touch_haptic_device/position.y
      - touch_haptic_device/position.z
      - touch_haptic_device/orientation.x
      - touch_haptic_device/orientation.y
      - touch_haptic_device/orientation.z
      - touch_haptic_device/orientation.w

    filter_chain:
      filter1:
        name: "moving_average_poses_filter"
        type: "moving_average_poses_filter/MovingAveragePosesFilter"
        params:
          number_of_observations: 50
