# This file contains the configuration of effort controllers used in simulation

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    pid_effort_controller:
      type: pid_controller/PidController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    gains:
      shoulder_pan_joint: {p: 1000.0, i: 5.0, d: 250.0, ff_velocity_scale: 0.0}
      shoulder_lift_joint: {p: 10000.0, i: 10.0, d: 700.0, ff_velocity_scale: 0.0}
      elbow_joint: {p: 5000.0, i: 10.0, d: 250.0, ff_velocity_scale: 0.0}
      wrist_1_joint: {p: 1000.0, i: 4.0, d: 10.0, ff_velocity_scale: 0.0}
      wrist_2_joint: {p: 500.0, i: 3.0, d: 5.0, ff_velocity_scale: 0.0}
      wrist_3_joint: {p: 30.0, i: 2.0, d: 0.05, ff_velocity_scale: 0.0}

pid_effort_controller:
  ros__parameters:
    dof_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interface: effort
    reference_and_state_interfaces: ["position", "effort"]
    gains:
      shoulder_pan_joint: {p: 1000.0, i: 5.0, d: 250.0}
      shoulder_lift_joint: {p: 10000.0, i: 10.0, d: 700.0}
      elbow_joint: {p: 5000.0, i: 10.0, d: 250.0}
      wrist_1_joint: {p: 1000.0, i: 4.0, d: 10.0}
      wrist_2_joint: {p: 500.0, i: 3.0, d: 5.0}
      wrist_3_joint: {p: 30.0, i: 2.0, d: 0.05}
