ft_sensor_mounting:
  description_package: "acg_resources_generic_mounting_description"
  description_file: "urdf/generic_mounting.urdf.xacro"
  description_params:
    height: 0.01
    radius: 0.05
    mass: 0.05

force_torque_sensor:
  description_package: "acg_resources_generic_force_torque_sensor_description"
  description_file: "urdf/generic_force_torque_sensor.urdf.xacro"
  description_params:
    height: 0.04
    radius: 0.05
    mass: 0.440
  ros2_control_package: "acg_resources_ft_sensor_gazebo_description"
  ros2_control_file: "urdf/gazebo_force_torque_sensor.ros2_control.xacro"
  ros2_control_params:
    number_of_samples_for_computing_bias: 10
    stable_readings_tolerance: 1e-2
  gazebo_params:
    topic: "force_torque"
    update_rate: 100

tool:
  description_package: "acg_resources_short_handle_description"
  description_file: "urdf/short_handle.urdf.xacro"

ignored_collision_links:
  - "wrist_1_link"
  - "wrist_2_link"
  - "wrist_3_link"
