# This file contains the configuration of controllers used in simulation, plus a f/t sensor broadcaster

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    task_space_reference_generator:
      type: task_space_reference_generator/TaskSpaceReferenceGenerator

    admittance_controller:
      type: acg_admittance_controller/AdmittanceController

    cartesian_pose_controller:
      type: cartesian_pose_controller/CartesianPoseController

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: gazebo_force_torque_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: ft_sensing_frame

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

task_space_reference_generator:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_interfaces:
      - position
      - velocity
    robot_name: ur10
    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity
    task_space_command_controller: "admittance_controller"
    task_space_command_interfaces:
      - pose
      - wrench
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: short_handle
    task_space_reference_frame: world
    wrench_reference_frame: ft_sensing_frame
    publish_reference: true
    publish_period: 1.0

admittance_controller:
  ros__parameters:
    robot_name: ur10
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    force_torque_sensor:
      name: gazebo_force_torque_sensor
      measure_frame: ft_sensing_frame
    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity
    command_interfaces:
      - pose
    reference_interfaces:
      - pose
      - wrench
    kinematics:
        plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
        plugin_package: kinematics_interface
        tip: short_handle
    task_space_reference_frame: world
    interaction_filter:
      type: interaction_filters/AdmittanceFilter
      name: admittance_filter
    wrench_reference_frame: ft_sensing_frame
    task_space_command_controller: cartesian_pose_controller
    fixed_robot_orientation: false
    command_tolerance:
      translational_tolerance: 0.5
      rotational_tolerance: 0.5
    filter_chain:
      fixed_orientation:
        filter1:
          name: "unbiasing_filter"
          type: "unbiasing_filter/UnbiasingFilterDouble"
          params:
            number_of_stable_samples_for_bias: 50
            tolerance: 2.0
        filter2:
          name: "multi_channel_moving_average_filter"
          type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
          params:
            number_of_observations: 15
      variable_orientation:
        filter1:
          name: "gravity_compensation_filter"
          type: "gravity_compensation_filter/GravityCompensationFilterDouble"
          params:
            ft_sensing_frame_name: "ft_sensing_frame"
            gravity: [0.0, 0.0, -9.81]
        filter2:
          name: "unbiasing_filter"
          type: "unbiasing_filter/UnbiasingFilterDouble"
          params:
            number_of_stable_samples_for_bias: 50
            tolerance: 2.0
        filter3:
          name: "multi_channel_moving_average_filter"
          type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
          params:
            number_of_observations: 15

    force_limitation_enabled: false
    reference_scaling_gain: 0.006  # Must be set between 0.0 and 1.0
    filter_chain_scaling:
      filter1:
        name: "multi_channel_moving_average_filter_scaling"
        type: "moving_average_filter/MultiChannelMovingAverageFilterDouble"
        params:
          number_of_observations: 150
    logging_enabled: true

    admittance_filter:
      mass:
        - 10.0
        - 10.0
        - 1000.0
        - 10.0
        - 5.0
        - 10.0
      damping_ratio:
        - 11.40
        - 11.40
        - 8.33
        - 11.40
        - 2.0
        - 11.40
      stiffness:
        - 1300.0
        - 1300.0
        - 90.0
        - 1300.0
        - 20.0
        - 1300.0
      order: 2  # Must be 0, 1 or 2
      compliant_axis: [true, true, true, false, true, true]

cartesian_pose_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    robot_name: ur10

    use_velocity_state_interfaces: true
    use_task_space_twist: false

    state_interfaces_names_override:
      position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position
      velocity:
        - shoulder_pan_joint/velocity
        - shoulder_lift_joint/velocity
        - elbow_joint/velocity
        - wrist_1_joint/velocity
        - wrist_2_joint/velocity
        - wrist_3_joint/velocity

    joint_space_command_controller: "none"
    command_interfaces:
      - position
    command_interfaces_names_override:
      joint_position:
        - shoulder_pan_joint/position
        - shoulder_lift_joint/position
        - elbow_joint/position
        - wrist_1_joint/position
        - wrist_2_joint/position
        - wrist_3_joint/position

    task_space_reference_frame: world

    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      tip: short_handle

    alpha: 0.000005
    k_matrix_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    joint_position_limits: [6.2832, 6.2832, 3.14159, 6.2832, 6.2832, 6.2832 ]
    joint_position_tolerance: 0.5
